# Generated by Django 3.1.6 on 2021-02-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human_id', models.IntegerField()),
                ('year', models.CharField(max_length=10)),
                ('workplace', models.CharField(max_length=50)),
                ('janu', models.IntegerField(blank=True, default=0, null=True)),
                ('feb', models.IntegerField(blank=True, default=0, null=True)),
                ('mar', models.IntegerField(blank=True, default=0, null=True)),
                ('apl', models.IntegerField(blank=True, default=0, null=True)),
                ('may', models.IntegerField(blank=True, default=0, null=True)),
                ('jun', models.IntegerField(blank=True, default=0, null=True)),
                ('jul', models.IntegerField(blank=True, default=0, null=True)),
                ('aug', models.IntegerField(blank=True, default=0, null=True)),
                ('sep', models.IntegerField(blank=True, default=0, null=True)),
                ('octr', models.IntegerField(blank=True, default=0, null=True)),
                ('nov', models.IntegerField(blank=True, default=0, null=True)),
                ('dec', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
