# Generated by Django 3.1.6 on 2021-02-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210205_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='good',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='read',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
