# Generated by Django 3.1.6 on 2021-02-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20210207_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='readtext',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
